# Generated by Django 3.1.2 on 2021-03-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='isInitialIncome',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
